---

#CREO L'AMBIENTE LIFERAY SULLA MACCHINA TARGET

#Creo la cartella w1 all'interno della macchina target (se esiste gia non farà nulla)
- name: Creating or checking /w1 directory..... 
  ansible.builtin.file:
    path: /w1
    state: directory

#Copio e Decomprimo il file Con Tomcat nella directory /w1
- name: Unzip Tomcat folder in the w1 directory...
  ansible.builtin.unarchive:
    src:  "{{ tomcat_zip_path }}" 
    dest: /w1
    remore_src: yes

#Rinomino la cartella con tomcat
- name: Renaming tomcat folder
  shell: mv -v /w1/{{ tomcat }} /w1/tomcat

  #Svuoto la cartella /w1/tomcat/webapps/ e al suo interno creo la cartella ROOT
- name: Deleting webapps dir contains and create within ROOT dir
  shell: rm -rf /w1/tomcat/webapps/* && mkdir /w1/tomcat/webapps/ROOT
